MODULE MODEL_PHYSICS_MF_MOD
  USE YOMPHY3  , ONLY : TPHY3

  IMPLICIT NONE
  
  TYPE MODEL_PHYSICS_MF_TYPE

  TYPE(TPHY3)   :: YRPHY3 !! radiation-related parameters

  END TYPE MODEL_PHYSICS_MF_TYPE

END MODULE MODEL_PHYSICS_MF_MOD
